SERVICE_ID=${SERVICE_ID:0:10}
AGENT_ID="${SERVICE_NAME}-${POD_ORDER}"

CATALINA_OPTS="$CATALINA_OPTS -javaagent:$PINPOINT_AGENT_PATH/pinpoint-bootstrap-${PINPOINT_AGETN_VERSION}-SNAPSHOT.jar"
CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.agentId=${AGENT_ID:-${SERVICE_ID:-20150415}}"
CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.applicationName=${APP_NAME:-${SERVICE_NAME:-$HOSTNAME}}"
